- name: Setup Frontend Service for Roboshop
  hosts: frontend
  become: true
  vars:
    catalogue_host: "catalogue.daws-84s.space"
    user_host: "user.daws-84s.space"
    cart_host: "cart.daws-84s.space"
    shipping_host: "shipping.daws-84s.space"
    payment_host: "payment.daws-84s.space"
  tasks:
    - name: Disable default Nginx module
      shell: dnf module disable nginx -y

    - name: Enable Nginx 1.24 module
      shell: dnf module enable nginx:1.24 -y

    - name: Install Nginx
      dnf:
        name: nginx
        state: present

    - name: Enable and start Nginx service
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Remove default content from Nginx
      file:
        path: /usr/share/nginx/html/
        state: absent

    - name: Recreate Nginx html directory
      file:
        path: /usr/share/nginx/html/
        state: directory

    - name: Download frontend application content
      get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
        dest: /tmp/frontend.zip

    - name: Unzip frontend content
      unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Deploy Nginx configuration for Roboshop frontend
      copy:
        dest: /etc/nginx/nginx.conf
        content: |
          user nginx;
          worker_processes auto;
          error_log /var/log/nginx/error.log notice;
          pid /run/nginx.pid;

          include /usr/share/nginx/modules/*.conf;

          events {
              worker_connections 1024;
          }

          http {
              log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                                '$status $body_bytes_sent "$http_referer" '
                                '"$http_user_agent" "$http_x_forwarded_for"';

              access_log  /var/log/nginx/access.log  main;

              sendfile            on;
              tcp_nopush          on;
              keepalive_timeout   65;
              types_hash_max_size 4096;

              include             /etc/nginx/mime.types;
              default_type        application/octet-stream;

              include /etc/nginx/conf.d/*.conf;

              server {
                  listen       80;
                  listen       [::]:80;
                  server_name  _;
                  root         /usr/share/nginx/html;

                  include /etc/nginx/default.d/*.conf;

                  error_page 404 /404.html;
                  location = /404.html {
                  }

                  error_page 500 502 503 504 /50x.html;
                  location = /50x.html {
                  }

                  location /images/ {
                    expires 5s;
                    root   /usr/share/nginx/html;
                    try_files $uri /images/placeholder.jpg;
                  }
                  location /api/catalogue/ { proxy_pass http://{{ catalogue_host }}:8080/; }
                  location /api/user/ { proxy_pass http://{{ user_host }}:8080/; }
                  location /api/cart/ { proxy_pass http://{{ cart_host }}:8080/; }
                  location /api/shipping/ { proxy_pass http://{{ shipping_host }}:8080/; }
                  location /api/payment/ { proxy_pass http://{{ payment_host }}:8080/; }

                  location /health {
                    stub_status on;
                    access_log off;
                  }
              }
          }

    - name: Restart Nginx service to apply changes
      systemd:
        name: nginx
        state: restarted