---
# roboshop-ansible/mongodb.yaml

- name: Setup MongoDB for Roboshop
  hosts: mongodb
  become: true
  tasks:
    - name: Create MongoDB repo file
      copy:
        dest: /etc/yum.repos.d/mongo.repo
        content: |
          [mongodb-org-7.0]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/redhat/9/mongodb-org/7.0/x86_64/
          enabled=1
          gpgcheck=0

    - name: Install MongoDB
      dnf:
        name: mongodb-org
        state: present

    - name: Enable and start mongod service
      systemd:
        name: mongod
        enabled: yes
        state: started

    - name: Update mongod.conf to listen on all interfaces
      lineinfile:
        path: /etc/mongod.conf
        regexp: '^\s*bindIp:'
        line: '  bindIp: 0.0.0.0'
        backrefs: yes

    - name: Restart mongod to apply configuration changes
      systemd:
        name: mongod
        state: restarted

