- name: Setup MySQL for Roboshop
  hosts: mysql
  become: true
  tasks:
    - name: Install MySQL server
      dnf:
        name: mysql-server
        state: present

    - name: Enable and start MySQL service
      systemd:
        name: mysqld
        enabled: yes
        state: started

    - name: Set MySQL root password
      shell: mysql_secure_installation --set-root-pass RoboShop@1
      args:
        creates: /root/.mysql_secure_installation_done

    - name: Create a flag file to indicate secure installation has been done
      file:
        path: /root/.mysql_secure_installation_done
        state: touch