- name: Setup RabbitMQ for Roboshop
  hosts: rabbitmq
  become: true
  tasks:
    - name: Setup RabbitMQ yum repository
      copy:
        dest: /etc/yum.repos.d/rabbitmq.repo
        content: |
          [modern-erlang]
          name=modern-erlang-el9
          baseurl=https://yum1.novemberain.com/erlang/el/9/$basearch
                  https://yum2.novemberain.com/erlang/el/9/$basearch
                  https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/rpm/el/9/$basearch
          enabled=1
          gpgcheck=0

          [modern-erlang-noarch]
          name=modern-erlang-el9-noarch
          baseurl=https://yum1.novemberain.com/erlang/el/9/noarch
                  https://yum2.novemberain.com/erlang/el/9/noarch
                  https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/rpm/el/9/noarch
          enabled=1
          gpgcheck=0

          [modern-erlang-source]
          name=modern-erlang-el9-source
          baseurl=https://yum1.novemberain.com/erlang/el/9/SRPMS
                  https://yum2.novemberain.com/erlang/el/9/SRPMS
                  https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/rpm/el/9/SRPMS
          enabled=1
          gpgcheck=0

          [rabbitmq-el9]
          name=rabbitmq-el9
          baseurl=https://yum2.novemberain.com/rabbitmq/el/9/$basearch
                  https://yum1.novemberain.com/rabbitmq/el/9/$basearch
                  https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/rpm/el/9/$basearch
          enabled=1
          gpgcheck=0

          [rabbitmq-el9-noarch]
          name=rabbitmq-el9-noarch
          baseurl=https://yum2.novemberain.com/rabbitmq/el/9/noarch
                  https://yum1.novemberain.com/rabbitmq/el/9/noarch
                  https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/rpm/el/9/noarch
          enabled=1
          gpgcheck=0

    - name: Install RabbitMQ server
      dnf:
        name: rabbitmq-server
        state: present

    - name: Enable and start RabbitMQ service
      systemd:
        name: rabbitmq-server
        enabled: yes
        state: started

    - name: Add RabbitMQ user 'roboshop'
      shell: rabbitmqctl add_user roboshop roboshop123
      args:
        creates: /var/lib/rabbitmq/.rabbitmq_user_roboshop_created

    - name: Set permissions for roboshop user
      shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
      args:
        creates: /var/lib/rabbitmq/.rabbitmq_user_roboshop_permissions_set